#tomcat的配置
server:
  port: 8088
  error:
    path: /error
  servlet:
    session:
      timeout: 30m
    context-path: /boot
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    

#上传文件目录
upload:
  path:
    #正式目录
    formal: D:/java/         #D:/java/(windows路径)      
   

#Linux环境的目录
#upload:
#  path:
#    #正式目录
#    formal: /usr/java/
 

spring:
#配置返回json格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss 
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false  
      
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
#文件上传最大大小
  servlet:
    multipart:
      max-file-size: 1MB
      
#缓存配置      
  cache:
    type: redis
    redis:
      time-to-live: 1800s

#数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/book?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: ooq666

#redis连接配置
  redis:
    database: 0
    host: 127.0.0.1
    password: ooq666
    port: 6379
#资源访问
  resources:
    static-locations: file:${upload.path.formal},classpath:/static/
#编码 
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.freedom.boot.bean
           
#分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

